version: "3"
services:
  jekyll:
    container_name: local_jekyll
    build:
      context: .
    image: jekyll
    volumes:
      - ./_site:/usr/src/app/_site
    ports:
      - "4000:4000"
    tty: true
